FROM debian:wheezy

RUN apt-get update
RUN apt-get -y install rake gnupg curl

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/4.8.0.495 main" | tee /etc/apt/sources.list.d/mono-official.list
RUN apt-get update
RUN apt-get -y install mono-devel mono-complete mono-dbg referenceassemblies-pcl ca-certificates-mono mono-xsp4 mono-xbuild mono-vbnc binutils fsharp nuget libnewtonsoft-json-cil-dev libnewtonsoft-json4.5-cil

WORKDIR /braintree-dotnet
