sonar.projectKey=BT-dotnet-ssdk
sonar.projectName=braintree-dotnet
sonar.sources=src
sonar.tests=test
sonar.cs.opencover.reportsPaths=test/Braintree.Tests/coverage/coverage.netcoreapp3.1.opencover.xml
